import os
import tempfile
from unittest.mock import MagicMock, patch

import pytest

from safe_pip_compile.core import run_safe_compile
from safe_pip_compile.models import (
    CompileStatus,
    ResolvedPackage,
    Severity,
    Vulnerability,
)
from safe_pip_compile.pip_compile import PipCompileResult
from safe_pip_compile.reporter import Reporter


@pytest.fixture
def mock_reporter():
    reporter = MagicMock(spec=Reporter)
    return reporter


@pytest.fixture
def tmp_output(tmp_path):
    output = tmp_path / "requirements.txt"
    return str(output)


def _write_reqs(path, content):
    with open(path, "w") as f:
        f.write(content)


CLEAN_REQS = (
    "# autogenerated\n"
    "django==4.2.7\n"
    "requests==2.31.0\n"
)

VULN_REQS = (
    "# autogenerated\n"
    "django==3.2.1\n"
    "requests==2.28.0\n"
)

FIXED_REQS = (
    "# autogenerated\n"
    "django==3.2.25\n"
    "requests==2.31.0\n"
)


@patch("safe_pip_compile.core.run_pip_compile")
@patch("safe_pip_compile.core.OSVClient")
def test_clean_on_first_pass(MockOSV, mock_pip_compile, mock_reporter, tmp_output):
    _write_reqs(tmp_output, CLEAN_REQS)

    mock_pip_compile.return_value = PipCompileResult(0, "", "")

    osv_instance = MockOSV.return_value
    osv_instance.batch_query.return_value = {}
    osv_instance.close = MagicMock()

    result = run_safe_compile(
        src_files=["requirements.in"],
        output_file=tmp_output,
        passthrough_args=[],
        min_severity=Severity.LOW,
        allowlist=[],
        max_iterations=10,
        dry_run=False,
        reporter=mock_reporter,
    )

    assert result.status == CompileStatus.CLEAN
    assert len(result.iterations) == 1


@patch("safe_pip_compile.core.run_pip_compile")
@patch("safe_pip_compile.core.OSVClient")
def test_one_iteration_fix(MockOSV, mock_pip_compile, mock_reporter, tmp_output):
    call_count = [0]

    def pip_compile_side_effect(*args, **kwargs):
        call_count[0] += 1
        if call_count[0] == 1:
            _write_reqs(tmp_output, VULN_REQS)
        else:
            _write_reqs(tmp_output, FIXED_REQS)
        return PipCompileResult(0, "", "")

    mock_pip_compile.side_effect = pip_compile_side_effect

    osv_instance = MockOSV.return_value
    osv_instance.close = MagicMock()

    def batch_query_side_effect(packages):
        for p in packages:
            if p.name == "django" and p.version == "3.2.1":
                return {"django": ["GHSA-test-1"]}
        return {}

    osv_instance.batch_query.side_effect = batch_query_side_effect
    osv_instance.fetch_vulnerabilities.return_value = [
        Vulnerability(
            id="GHSA-test-1",
            aliases=("CVE-2024-00001",),
            severity=Severity.HIGH,
            affected_package="django",
            affected_version="3.2.1",
            fixed_versions=("3.2.25",),
        )
    ]

    result = run_safe_compile(
        src_files=["requirements.in"],
        output_file=tmp_output,
        passthrough_args=[],
        min_severity=Severity.LOW,
        allowlist=[],
        max_iterations=10,
        dry_run=False,
        reporter=mock_reporter,
    )

    assert result.status == CompileStatus.CLEAN
    assert len(result.iterations) == 2


@patch("safe_pip_compile.core.run_pip_compile")
def test_pip_compile_initial_failure(mock_pip_compile, mock_reporter, tmp_output):
    mock_pip_compile.return_value = PipCompileResult(
        1, "", "Could not find a version that satisfies the requirement"
    )

    from safe_pip_compile.exceptions import PipCompileError

    with pytest.raises(PipCompileError, match="Initial pip-compile failed"):
        run_safe_compile(
            src_files=["requirements.in"],
            output_file=tmp_output,
            passthrough_args=[],
            min_severity=Severity.LOW,
            allowlist=[],
            max_iterations=10,
            dry_run=False,
            reporter=mock_reporter,
        )


@patch("safe_pip_compile.core.run_pip_compile")
@patch("safe_pip_compile.core.OSVClient")
def test_severity_filtering(MockOSV, mock_pip_compile, mock_reporter, tmp_output):
    _write_reqs(tmp_output, VULN_REQS)
    mock_pip_compile.return_value = PipCompileResult(0, "", "")

    osv_instance = MockOSV.return_value
    osv_instance.close = MagicMock()
    osv_instance.batch_query.return_value = {"django": ["V1"]}
    osv_instance.fetch_vulnerabilities.return_value = [
        Vulnerability(
            id="V1",
            severity=Severity.MEDIUM,
            affected_package="django",
            affected_version="3.2.1",
            fixed_versions=("3.2.25",),
        )
    ]

    result = run_safe_compile(
        src_files=["requirements.in"],
        output_file=tmp_output,
        passthrough_args=[],
        min_severity=Severity.HIGH,
        allowlist=[],
        max_iterations=10,
        dry_run=False,
        reporter=mock_reporter,
    )

    assert result.status == CompileStatus.CLEAN


@patch("safe_pip_compile.core.run_pip_compile")
@patch("safe_pip_compile.core.OSVClient")
def test_unfixable_cves(MockOSV, mock_pip_compile, mock_reporter, tmp_output):
    _write_reqs(tmp_output, VULN_REQS)
    mock_pip_compile.return_value = PipCompileResult(0, "", "")

    osv_instance = MockOSV.return_value
    osv_instance.close = MagicMock()
    osv_instance.batch_query.return_value = {"django": ["V1"]}
    osv_instance.fetch_vulnerabilities.return_value = [
        Vulnerability(
            id="V1",
            severity=Severity.CRITICAL,
            affected_package="nonexistent-pkg",
            affected_version="3.2.1",
            fixed_versions=(),
        )
    ]

    result = run_safe_compile(
        src_files=["requirements.in"],
        output_file=tmp_output,
        passthrough_args=[],
        min_severity=Severity.LOW,
        allowlist=[],
        max_iterations=10,
        dry_run=False,
        reporter=mock_reporter,
    )

    assert result.status == CompileStatus.UNFIXABLE_CVES
